import { MediaContent, Event, Product, DigitalBook } from '@/types/ecosystem';

// Mock Events Data
export const MOCK_EVENTS: Event[] = [
  {
    id: 'event-1',
    title: 'Weekly Tafsir Session',
    description: 'Join us for a weekly Tafsir session where we explore the meanings and interpretations of the Quran. This session is open to all community members.',
    start_time: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days from now
    end_time: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    location_name: 'Masjid Al-Amin, Dakar',
    is_online: false,
    max_attendees: 100,
    image_url: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: 'event-2',
    title: 'Islamic Finance Workshop',
    description: 'Learn about Islamic banking principles, halal investments, and financial planning according to Shariah law. Expert speakers will cover practical applications.',
    start_time: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(), // 14 days from now
    end_time: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    location_name: 'Islamic Center, Thiès',
    is_online: false,
    max_attendees: 50,
    image_url: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: 'event-3',
    title: 'Online Hadith Study Circle',
    description: 'Virtual study circle focusing on authentic Hadith collections. Perfect for those who want to deepen their understanding of the Prophet\'s teachings.',
    start_time: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days from now
    end_time: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
    location_name: 'Online (Zoom)',
    is_online: true,
    max_attendees: 200,
    image_url: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: 'event-4',
    title: 'Youth Islamic Camp',
    description: 'A weekend camp for Muslim youth focusing on character building, Islamic values, and community service. Activities include sports, workshops, and group discussions.',
    start_time: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(), // 21 days from now
    end_time: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString(),
    location_name: 'Islamic Retreat Center, Mbour',
    is_online: false,
    max_attendees: 75,
    image_url: undefined,
    created_at: new Date().toISOString(),
  },
];

// Mock Videos Data
export const MOCK_VIDEOS: MediaContent[] = [
  {
    id: 'video-1',
    title: 'Introduction to Islamic Jurisprudence (Fiqh)',
    description: 'A comprehensive introduction to the principles of Islamic jurisprudence, covering the four major schools of thought and their methodologies.',
    type: 'video',
    url: 'https://example.com/video1.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800',
    duration_seconds: 1800, // 30 minutes
    language: 'fr',
    audience: 'adults',
    transcript: 'Introduction to Fiqh...',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'video-2',
    title: 'Stories of the Prophets for Kids',
    description: 'Engaging animated stories about the Prophets of Islam, designed to teach children about faith, patience, and good character.',
    type: 'video',
    url: 'https://example.com/video2.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800',
    duration_seconds: 900, // 15 minutes
    language: 'wo',
    audience: 'kids',
    transcript: 'Stories of the Prophets...',
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'video-3',
    title: 'Understanding Zakat: A Practical Guide',
    description: 'Learn how to calculate and distribute Zakat according to Islamic principles, with practical examples and case studies.',
    type: 'video',
    url: 'https://example.com/video3.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
    duration_seconds: 2400, // 40 minutes
    language: 'fr',
    audience: 'adults',
    transcript: 'Understanding Zakat...',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'video-4',
    title: 'Teen Talk: Navigating Modern Life as a Muslim',
    description: 'A discussion series for teenagers addressing common challenges, peer pressure, social media, and maintaining Islamic values in today\'s world.',
    type: 'video',
    url: 'https://example.com/video4.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800',
    duration_seconds: 1200, // 20 minutes
    language: 'en',
    audience: 'teens',
    transcript: 'Teen Talk...',
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'video-5',
    title: 'The Life of Prophet Muhammad (PBUH)',
    description: 'A detailed documentary series covering the life, character, and teachings of Prophet Muhammad (peace be upon him).',
    type: 'video',
    url: 'https://example.com/video5.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    duration_seconds: 3600, // 60 minutes
    language: 'fr',
    audience: 'adults',
    transcript: 'The Life of Prophet Muhammad...',
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'video-6',
    title: 'Arabic Alphabet for Beginners',
    description: 'Fun and interactive lessons for children to learn the Arabic alphabet, with songs, games, and practice exercises.',
    type: 'video',
    url: 'https://example.com/video6.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    duration_seconds: 600, // 10 minutes
    language: 'wo',
    audience: 'kids',
    transcript: 'Arabic Alphabet...',
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Products Data
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'product-1',
    name: 'Islamic Prayer Rug - Premium Quality',
    description: 'Handwoven prayer rug with beautiful geometric patterns. Made from high-quality materials, perfect for daily prayers.',
    price: 25000,
    currency: 'XOF',
    stock_quantity: 45,
    images: ['https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800'],
    category: 'accessories',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-2',
    name: 'Quran with French Translation',
    description: 'Complete Quran with French translation and commentary. Hardcover edition with beautiful calligraphy.',
    price: 15000,
    currency: 'XOF',
    stock_quantity: 30,
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800'],
    category: 'books',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-3',
    name: 'Modest Abaya - Black',
    description: 'Elegant black abaya made from premium fabric. Perfect for daily wear, comfortable and stylish.',
    price: 35000,
    currency: 'XOF',
    stock_quantity: 20,
    images: ['https://images.unsplash.com/photo-1594633312681-425a7b93aa88?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-4',
    name: 'Tasbih (Prayer Beads) - 99 Beads',
    description: 'Traditional prayer beads made from high-quality materials. Perfect for dhikr and remembrance of Allah.',
    price: 5000,
    currency: 'XOF',
    stock_quantity: 100,
    images: ['https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800'],
    category: 'accessories',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-5',
    name: 'Islamic Calendar 2025',
    description: 'Beautiful wall calendar with Islamic dates, prayer times, and important Islamic events. Features stunning calligraphy.',
    price: 8000,
    currency: 'XOF',
    stock_quantity: 60,
    images: ['https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800'],
    category: 'accessories',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-6',
    name: 'Hijab Collection - Assorted Colors',
    description: 'Premium quality hijabs in various colors and styles. Soft, breathable fabric perfect for all seasons.',
    price: 12000,
    currency: 'XOF',
    stock_quantity: 50,
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-7',
    name: 'Islamic Children\'s Book Set',
    description: 'Set of 10 illustrated books teaching Islamic values, stories of prophets, and basic Islamic knowledge for children.',
    price: 20000,
    currency: 'XOF',
    stock_quantity: 25,
    images: ['https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=800'],
    category: 'books',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-8',
    name: 'Kufi Cap - Traditional Style',
    description: 'Traditional kufi cap made from premium cotton. Comfortable and stylish, perfect for daily wear.',
    price: 6000,
    currency: 'XOF',
    stock_quantity: 40,
    images: ['https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-9',
    name: 'Modest Jilbab - Navy Blue',
    description: 'Elegant navy blue jilbab with modern design. Perfect for formal occasions and daily wear.',
    price: 40000,
    currency: 'XOF',
    stock_quantity: 15,
    images: ['https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-10',
    name: 'Thobe for Men - White',
    description: 'Traditional white thobe made from breathable cotton. Perfect for prayers and special occasions.',
    price: 30000,
    currency: 'XOF',
    stock_quantity: 25,
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-11',
    name: 'Modest Dress - Long Sleeve',
    description: 'Comfortable long-sleeve dress in various colors. Perfect for everyday wear with modesty and style.',
    price: 28000,
    currency: 'XOF',
    stock_quantity: 30,
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-12',
    name: 'Islamic Streetwear T-Shirt',
    description: 'Comfortable and stylish t-shirt with Islamic designs. Made from premium cotton, perfect for casual wear.',
    price: 15000,
    currency: 'XOF',
    stock_quantity: 50,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
];

// Mock Digital Library Data
export const MOCK_BOOKS: DigitalBook[] = [
  {
    id: 'book-1',
    title: 'Understanding the Quran: A Thematic Commentary',
    author: 'Dr. Muhammad Asad',
    description: 'A comprehensive thematic commentary on the Quran, providing deep insights into the divine message with modern context and classical scholarship.',
    category: 'tafsir',
    language: 'en',
    format: 'pdf',
    file_url: '/books/understanding-quran.pdf',
    cover_image_url: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400',
    page_count: 450,
    file_size_mb: 12.5,
    isbn: '978-1234567890',
    publisher: 'Islamic Foundation',
    publication_year: 2020,
    downloads: 1250,
    featured: true,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'book-2',
    title: 'Sahih Al-Bukhari - Complete Collection',
    author: 'Imam Bukhari',
    description: 'The most authentic collection of Hadith compiled by Imam Bukhari. This edition includes Arabic text with English translation and commentary.',
    category: 'hadith',
    language: 'en',
    format: 'pdf',
    file_url: '/books/sahih-bukhari.pdf',
    cover_image_url: 'https://images.unsplash.com/photo-1585779034823-7e9ac8faec70?w=400',
    page_count: 850,
    file_size_mb: 25.8,
    isbn: '978-9876543210',
    publisher: 'Dar-us-Salam',
    publication_year: 2019,
    downloads: 3450,
    featured: true,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'book-3',
    title: 'Fiqh According to the Maliki School',
    author: 'Sheikh Abdullah ibn Abi Zayd al-Qayrawani',
    description: 'A comprehensive guide to Islamic jurisprudence according to the Maliki school of thought. Essential reading for understanding Maliki fiqh.',
    category: 'fiqh',
    language: 'en',
    format: 'pdf',
    file_url: '/books/maliki-fiqh.pdf',
    cover_image_url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
    page_count: 620,
    file_size_mb: 18.2,
    isbn: '978-5432109876',
    publisher: 'Zaytuna Institute',
    publication_year: 2021,
    downloads: 890,
    featured: true,
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'book-4',
    title: 'Le Saint Coran avec Traduction Française',
    author: 'Traduction par Muhammad Hamidullah',
    description: 'Une traduction française authentique et précise du Saint Coran par le Dr. Muhammad Hamidullah, avec annotations et commentaires.',
    category: 'quran',
    language: 'fr',
    format: 'pdf',
    file_url: '/books/quran-french.pdf',
    cover_image_url: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=400',
    page_count: 720,
    file_size_mb: 15.3,
    publisher: 'Centre Culturel Islamique',
    publication_year: 2018,
    downloads: 2100,
    featured: false,
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'book-5',
    title: 'Aqeedah At-Tahawiyyah',
    author: 'Imam Abu Ja\'far al-Tahawi',
    description: 'A foundational text on Islamic creed (Aqeedah) that presents the core beliefs of Ahlus Sunnah wal Jama\'ah in a clear and concise manner.',
    category: 'aqeedah',
    language: 'en',
    format: 'pdf',
    file_url: '/books/aqeedah-tahawiyyah.pdf',
    cover_image_url: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400',
    page_count: 180,
    file_size_mb: 5.2,
    isbn: '978-1122334455',
    publisher: 'Beacon Books',
    publication_year: 2020,
    downloads: 1680,
    featured: false,
    created_at: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'book-6',
    title: 'The Sealed Nectar (Ar-Raheeq Al-Makhtum)',
    author: 'Safi-ur-Rahman al-Mubarakpuri',
    description: 'An award-winning biography of Prophet Muhammad (PBUH). This comprehensive work covers the life and mission of the Prophet in great detail.',
    category: 'seerah',
    language: 'en',
    format: 'pdf',
    file_url: '/books/sealed-nectar.pdf',
    cover_image_url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
    page_count: 592,
    file_size_mb: 16.7,
    isbn: '978-9960899558',
    publisher: 'Darussalam',
    publication_year: 2017,
    downloads: 4200,
    featured: true,
    created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'book-7',
    title: 'Gateway to Arabic - Book 1',
    author: 'Dr. Imran Hamza Alawiye',
    description: 'A comprehensive introduction to Arabic language learning designed for English speakers. Perfect for beginners wanting to learn Quranic Arabic.',
    category: 'arabic',
    language: 'en',
    format: 'pdf',
    file_url: '/books/gateway-arabic.pdf',
    cover_image_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400',
    page_count: 240,
    file_size_mb: 8.5,
    isbn: '978-0954750312',
    publisher: 'Arabic Institute',
    publication_year: 2019,
    downloads: 1540,
    featured: false,
    created_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'book-8',
    title: 'Fortress of the Muslim (Hisn al-Muslim)',
    author: 'Sa\'id ibn Wahf al-Qahtani',
    description: 'A collection of authentic supplications and dhikr from the Quran and Sunnah for daily life, organized by occasion and time.',
    category: 'dua',
    language: 'en',
    format: 'pdf',
    file_url: '/books/fortress-muslim.pdf',
    cover_image_url: 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400',
    page_count: 156,
    file_size_mb: 4.8,
    isbn: '978-9960899305',
    publisher: 'Darussalam',
    publication_year: 2016,
    downloads: 2890,
    featured: false,
    created_at: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'book-9',
    title: 'Introduction à l\'Islam',
    author: 'Dr. Youssef Al-Qaradawi',
    description: 'Une introduction complète à l\'Islam, couvrant les principes fondamentaux, les pratiques et la spiritualité islamique.',
    category: 'general',
    language: 'fr',
    format: 'pdf',
    file_url: '/books/intro-islam-french.pdf',
    cover_image_url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    page_count: 340,
    file_size_mb: 10.2,
    publisher: 'Éditions Tawhid',
    publication_year: 2018,
    downloads: 980,
    featured: false,
    created_at: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'book-10',
    title: 'Tafsir Ibn Kathir (Abridged)',
    author: 'Imam Ibn Kathir',
    description: 'An abridged version of the famous Tafsir Ibn Kathir, one of the most respected and authentic commentaries on the Quran.',
    category: 'tafsir',
    language: 'en',
    format: 'pdf',
    file_url: '/books/tafsir-ibn-kathir.pdf',
    cover_image_url: 'https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=400',
    page_count: 1250,
    file_size_mb: 35.6,
    isbn: '978-9960892160',
    publisher: 'Darussalam',
    publication_year: 2018,
    downloads: 5600,
    featured: true,
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

