import { MediaContent, Event, Product } from '@/types/ecosystem';

// Mock Events Data
export const MOCK_EVENTS: Event[] = [
  {
    id: 'event-1',
    title: 'Weekly Tafsir Session',
    description: 'Join us for a weekly Tafsir session where we explore the meanings and interpretations of the Quran. This session is open to all community members.',
    start_time: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days from now
    end_time: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    location_name: 'Masjid Al-Amin, Dakar',
    is_online: false,
    max_attendees: 100,
    image_url: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: 'event-2',
    title: 'Islamic Finance Workshop',
    description: 'Learn about Islamic banking principles, halal investments, and financial planning according to Shariah law. Expert speakers will cover practical applications.',
    start_time: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(), // 14 days from now
    end_time: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    location_name: 'Islamic Center, Thiès',
    is_online: false,
    max_attendees: 50,
    image_url: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: 'event-3',
    title: 'Online Hadith Study Circle',
    description: 'Virtual study circle focusing on authentic Hadith collections. Perfect for those who want to deepen their understanding of the Prophet\'s teachings.',
    start_time: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days from now
    end_time: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
    location_name: 'Online (Zoom)',
    is_online: true,
    max_attendees: 200,
    image_url: undefined,
    created_at: new Date().toISOString(),
  },
  {
    id: 'event-4',
    title: 'Youth Islamic Camp',
    description: 'A weekend camp for Muslim youth focusing on character building, Islamic values, and community service. Activities include sports, workshops, and group discussions.',
    start_time: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(), // 21 days from now
    end_time: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString(),
    location_name: 'Islamic Retreat Center, Mbour',
    is_online: false,
    max_attendees: 75,
    image_url: undefined,
    created_at: new Date().toISOString(),
  },
];

// Mock Videos Data
export const MOCK_VIDEOS: MediaContent[] = [
  {
    id: 'video-1',
    title: 'Introduction to Islamic Jurisprudence (Fiqh)',
    description: 'A comprehensive introduction to the principles of Islamic jurisprudence, covering the four major schools of thought and their methodologies.',
    type: 'video',
    url: 'https://example.com/video1.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800',
    duration_seconds: 1800, // 30 minutes
    language: 'fr',
    audience: 'adults',
    transcript: 'Introduction to Fiqh...',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'video-2',
    title: 'Stories of the Prophets for Kids',
    description: 'Engaging animated stories about the Prophets of Islam, designed to teach children about faith, patience, and good character.',
    type: 'video',
    url: 'https://example.com/video2.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800',
    duration_seconds: 900, // 15 minutes
    language: 'wo',
    audience: 'kids',
    transcript: 'Stories of the Prophets...',
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'video-3',
    title: 'Understanding Zakat: A Practical Guide',
    description: 'Learn how to calculate and distribute Zakat according to Islamic principles, with practical examples and case studies.',
    type: 'video',
    url: 'https://example.com/video3.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
    duration_seconds: 2400, // 40 minutes
    language: 'fr',
    audience: 'adults',
    transcript: 'Understanding Zakat...',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'video-4',
    title: 'Teen Talk: Navigating Modern Life as a Muslim',
    description: 'A discussion series for teenagers addressing common challenges, peer pressure, social media, and maintaining Islamic values in today\'s world.',
    type: 'video',
    url: 'https://example.com/video4.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800',
    duration_seconds: 1200, // 20 minutes
    language: 'en',
    audience: 'teens',
    transcript: 'Teen Talk...',
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'video-5',
    title: 'The Life of Prophet Muhammad (PBUH)',
    description: 'A detailed documentary series covering the life, character, and teachings of Prophet Muhammad (peace be upon him).',
    type: 'video',
    url: 'https://example.com/video5.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    duration_seconds: 3600, // 60 minutes
    language: 'fr',
    audience: 'adults',
    transcript: 'The Life of Prophet Muhammad...',
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'video-6',
    title: 'Arabic Alphabet for Beginners',
    description: 'Fun and interactive lessons for children to learn the Arabic alphabet, with songs, games, and practice exercises.',
    type: 'video',
    url: 'https://example.com/video6.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    duration_seconds: 600, // 10 minutes
    language: 'wo',
    audience: 'kids',
    transcript: 'Arabic Alphabet...',
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Products Data
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'product-1',
    name: 'Islamic Prayer Rug - Premium Quality',
    description: 'Handwoven prayer rug with beautiful geometric patterns. Made from high-quality materials, perfect for daily prayers.',
    price: 25000,
    currency: 'XOF',
    stock_quantity: 45,
    images: ['https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800'],
    category: 'accessories',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-2',
    name: 'Quran with French Translation',
    description: 'Complete Quran with French translation and commentary. Hardcover edition with beautiful calligraphy.',
    price: 15000,
    currency: 'XOF',
    stock_quantity: 30,
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800'],
    category: 'books',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-3',
    name: 'Modest Abaya - Black',
    description: 'Elegant black abaya made from premium fabric. Perfect for daily wear, comfortable and stylish.',
    price: 35000,
    currency: 'XOF',
    stock_quantity: 20,
    images: ['https://images.unsplash.com/photo-1594633312681-425a7b93aa88?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-4',
    name: 'Tasbih (Prayer Beads) - 99 Beads',
    description: 'Traditional prayer beads made from high-quality materials. Perfect for dhikr and remembrance of Allah.',
    price: 5000,
    currency: 'XOF',
    stock_quantity: 100,
    images: ['https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800'],
    category: 'accessories',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-5',
    name: 'Islamic Calendar 2024',
    description: 'Beautiful wall calendar with Islamic dates, prayer times, and important Islamic events. Features stunning calligraphy.',
    price: 8000,
    currency: 'XOF',
    stock_quantity: 60,
    images: ['https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800'],
    category: 'accessories',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-6',
    name: 'Hijab Collection - Assorted Colors',
    description: 'Premium quality hijabs in various colors and styles. Soft, breathable fabric perfect for all seasons.',
    price: 12000,
    currency: 'XOF',
    stock_quantity: 50,
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-7',
    name: 'Islamic Children\'s Book Set',
    description: 'Set of 10 illustrated books teaching Islamic values, stories of prophets, and basic Islamic knowledge for children.',
    price: 20000,
    currency: 'XOF',
    stock_quantity: 25,
    images: ['https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=800'],
    category: 'books',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-8',
    name: 'Kufi Cap - Traditional Style',
    description: 'Traditional kufi cap made from premium cotton. Comfortable and stylish, perfect for daily wear.',
    price: 6000,
    currency: 'XOF',
    stock_quantity: 40,
    images: ['https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-9',
    name: 'Modest Jilbab - Navy Blue',
    description: 'Elegant navy blue jilbab with modern design. Perfect for formal occasions and daily wear.',
    price: 40000,
    currency: 'XOF',
    stock_quantity: 15,
    images: ['https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-10',
    name: 'Thobe for Men - White',
    description: 'Traditional white thobe made from breathable cotton. Perfect for prayers and special occasions.',
    price: 30000,
    currency: 'XOF',
    stock_quantity: 25,
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-11',
    name: 'Modest Dress - Long Sleeve',
    description: 'Comfortable long-sleeve dress in various colors. Perfect for everyday wear with modesty and style.',
    price: 28000,
    currency: 'XOF',
    stock_quantity: 30,
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
  {
    id: 'product-12',
    name: 'Islamic Streetwear T-Shirt',
    description: 'Comfortable and stylish t-shirt with Islamic designs. Made from premium cotton, perfect for casual wear.',
    price: 15000,
    currency: 'XOF',
    stock_quantity: 50,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800'],
    category: 'clothing',
    created_at: new Date().toISOString(),
  },
];

